// styles.js — Shared style objects to keep components clean
// Using plain objects (not CSS files) keeps everything in one place for this project

export const s = {
  page: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "#F9FAFB",
  },
  card: {
    width: "100%",
    maxWidth: 420,
    background: "#fff",
    padding: 32,
    borderRadius: 12,
    border: "1px solid #E5E7EB",
    boxShadow: "0 1px 3px rgba(0,0,0,0.08)",
  },
  heading: { margin: "0 0 24px", fontSize: 22, fontWeight: 600 },
  form: { display: "flex", flexDirection: "column", gap: 12 },
  label: { fontSize: 13, fontWeight: 500, color: "#374151", marginBottom: 2 },
  input: {
    width: "100%",
    padding: "10px 12px",
    fontSize: 14,
    border: "1px solid #D1D5DB",
    borderRadius: 8,
    boxSizing: "border-box",
    outline: "none",
  },
  btn: {
    padding: "11px 20px",
    background: "#4F46E5",
    color: "#fff",
    border: "none",
    borderRadius: 8,
    cursor: "pointer",
    fontSize: 14,
    fontWeight: 500,
  },
  btnSm: {
    padding: "6px 14px",
    background: "#4F46E5",
    color: "#fff",
    border: "none",
    borderRadius: 6,
    cursor: "pointer",
    fontSize: 13,
  },
  errorBox: {
    background: "#FEF2F2",
    color: "#991B1B",
    padding: "10px 14px",
    borderRadius: 8,
    fontSize: 13,
    marginBottom: 8,
  },
  successBox: {
    background: "#F0FDF4",
    color: "#166534",
    padding: "10px 14px",
    borderRadius: 8,
    fontSize: 13,
    marginBottom: 8,
  },
  sub: { textAlign: "center", marginTop: 16, fontSize: 13, color: "#6B7280" },
};
